"""
YAML configuration file generation for ingested datasets.
"""

from pathlib import Path
from typing import List, Optional
from datetime import datetime
import logging

from airtrace.utils.config_paths import get_default_config_write_path

logger = logging.getLogger(__name__)


class ConfigGenerator:
    """Generates Hydra YAML configuration for datasets."""

    def __init__(
        self,
        dataset_name: str,
        sensors: List[str],
        input_len: int,
        pred_len: int,
        stride: int,
        target_sensors: List[str]
    ):
        """
        Args:
            dataset_name: Name of the dataset
            sensors: List of all sensor names
            input_len: Input sequence length
            pred_len: Prediction sequence length
            stride: Sliding window stride
            target_sensors: List of sensors to predict
        """
        self.dataset_name = dataset_name
        self.sensors = sensors
        self.input_len = input_len
        self.pred_len = pred_len
        self.stride = stride
        self.target_sensors = target_sensors

    def generate(
        self,
        output_path: Optional[Path] = None,
        n_flights: int = 0,
        input_path: str = "",
        force: bool = False
    ):
        """
        Generate and save YAML config.

        If output_path is None, automatically determines the best location using:
          1. AIRTRACE_CONFIG_DIR environment variable (if set)
          2. User directory: ~/.airtrace/configs/data/ (default)
          3. Package directory (fallback, editable installs only)

        Args:
            output_path: Optional path to save YAML file (None = auto-detect)
            n_flights: Total number of flights (for header comment)
            input_path: Original input path (for header comment)
            force: Overwrite existing file

        Returns:
            None
        """
        # Auto-detect output path if not provided
        if output_path is None:
            output_path = get_default_config_write_path(self.dataset_name)
            logger.info(f"No output path specified, using default: {output_path}")
        else:
            output_path = Path(output_path)

        # Check if file exists
        if output_path.exists() and not force:
            logger.warning(f"Config file already exists: {output_path}")
            logger.warning("Use --force to overwrite")
            return

        # Create parent directory if needed
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build YAML content
        yaml_content = self._build_yaml(n_flights, input_path)

        # Write file
        with open(output_path, "w") as f:
            f.write(yaml_content)

        logger.info(f"Successfully wrote config to: {output_path}")

    def _build_yaml(self, n_flights: int, input_path: str) -> str:
        """Build YAML content string."""

        # Header with metadata
        header = f"""# @package _global_
# Auto-generated by airtrace ingest on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# Dataset: {self.dataset_name}
# Input path: {input_path}
# Total flights: {n_flights}
# Sensors: {len(self.sensors)}

"""

        # Data configuration
        config_lines = [
            "data:",
            "  root: data/",
            f'  dataset_name: "{self.dataset_name}"',
            f'  train_index: "metadata/{self.dataset_name}_train_index.parquet"',
            f'  val_index: "metadata/{self.dataset_name}_val_index.parquet"',
            f'  test_index: "metadata/{self.dataset_name}_test_index.parquet"',
            "",
            "  window:",
            f"    input_len: {self.input_len}",
            f"    pred_len: {self.pred_len}",
            f"    stride: {self.stride}",
            "    target_sensors:",
        ]

        # Add target sensors
        for sensor in self.target_sensors:
            config_lines.append(f'      - "{sensor}"')

        config_lines.extend([
            "",
            "  sensors:",
            "    use:",
        ])

        # Add all sensors
        for sensor in self.sensors:
            config_lines.append(f'      - "{sensor}"')

        config_lines.extend([
            "",
            "  static_features:",
            "    use: []",
        ])

        # Combine header and config
        yaml_content = header + "\n".join(config_lines) + "\n"

        return yaml_content
