defaults:
  - override /data: qantas_737
  - override /model: tcn
  - override /transforms: zscore_diff_with_context
  - override /task: multi_step
  - override /train: long_context

exp_name: "tcn_zscore_multi_step"
seed: 456
