defaults:
  - override /data: qantas_737
  - override /model: lag_llama
  - override /transforms: zscore_diff_with_context
  - override /task: one_step
  - override /train: default

exp_name: "lag_llama_retrieval_diffusion"
seed: 2025
