defaults:
  - override /data: qantas_737
  - override /model: patchtst
  - override /transforms: zscore_diff_with_context
  - override /task: one_step
  - override /train: default

exp_name: "patchtst_zscore_one_step"
seed: 123
