model:
  name: sarima
  params:
    order: [1, 1, 0]
    seasonal_order: [0, 0, 0, 0]
    trend: null
    enforce_stationarity: true
    enforce_invertibility: true
    maxiter: 50
    measurement_error: false
