# @package _global_

model:
  name: tft
  params:
    hidden_size: 128
    lstm_layers: 2
    num_heads: 4
    dropout: 0.1
    quantiles: [0.1, 0.5, 0.9]
    static_input_dim: 0
    known_future_dim: 0
    pred_len: 1
