# @package _global_

model:
  name: transformer
  params:
    d_model: 128
    nhead: 8
    num_encoder_layers: 4
    num_decoder_layers: 4
    dim_feedforward: 512
    dropout: 0.1
    activation: "gelu"
    causal: true
